// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppJob: typeof import('./src/components/AppJob.vue')['default']
    AppSideInfos: typeof import('./src/components/AppSideInfos.vue')['default']
    TheAboutSection: typeof import('./src/components/TheAboutSection.vue')['default']
    TheExperienceSection: typeof import('./src/components/TheExperienceSection.vue')['default']
    TheHeroSection: typeof import('./src/components/TheHeroSection.vue')['default']
    TheMailInfo: typeof import('./src/components/TheMailInfo.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheSocialNetworkLinks: typeof import('./src/components/TheSocialNetworkLinks.vue')['default']
  }
}
